# Data Ingestion and Preprocessing

Reads all dataset, preprocess them and fit into the schema for the analysis_of_bandit_algorithms jupyter notebook. Outputs preprocessed datasets into the data folder.

In [1]:
import pandas as pd

In [87]:
# All required directories / files
data_dir = './data/'
movie_review_dataset = 'top-n-movies_user-ratings.csv'
movie_review_output_path = './data/preprocessed_movie_ratings.csv'

## Movie Review Dataset

In [43]:
# Movie Reviews of Top 10 Movies
movie_reviews_df = pd.read_csv(data_dir + movie_review_dataset)
# movie_reviews_df.drop(movie_reviews_df.columns[0], inplace=True, axis=1)
movie_reviews_df

      Unnamed: 0  user_id  movie_id  rating           movie_title
0              0      307         0       4             Toy Story
1              1      250        99       4                 Fargo
2              2       24       180       5    Return of the Jedi
3              3       19       287       1                Scream
4              4       31       293       3             Liar Liar
5              5       43       293       4             Liar Liar
6              6       25       257       3               Contact
7              7      193       180       3    Return of the Jedi
8              8       65       257       4               Contact
9              9      206       257       4               Contact
10            10      190       285       4  English Patient, The
11            11      133       285       3  English Patient, The
12            12      286         0       5             Toy Story
13            13      285       287       5                Scream
14            14      289        49       5             Star Wars
15            15      263       293       3             Liar Liar
16            16      230       180       4    Return of the Jedi
17            17       55       120       5      Independence Day
18            18      297       180       4    Return of the Jedi
19            19        9        99       5                 Fargo
20            20      244       180       4    Return of the Jedi
21            21      180       120       4      Independence Day
22            22      275       180       5    Return of the Jedi
23            23      266       120       3      Independence Day
24            24      125       293       3             Liar Liar
25            25       36       287       4                Scream
26            26       89       257       3               Contact
27            27      107        99       4                 Fargo
28            28       91       120       5      Independence Day
29            29      253       120       3      Independence Day
...          ...      ...       ...     ...                   ...
4833        4833      894         0       4             Toy Story
4834        4834      381       285       2  English Patient, The
4835        4835      746         0       5             Toy Story
4836        4836      803       293       5             Liar Liar
4837        4837      736        99       5                 Fargo
4838        4838       56       120       4      Independence Day
4839        4839      733        49       4             Star Wars
4840        4840      748        49       5             Star Wars
4841        4841      656       257       2               Contact
4842        4842      805        99       4                 Fargo
4843        4843      540       257       4               Contact
4844        4844      785         0       4             Toy Story
4845        4845      866       293       3             Liar Liar
4846        4846      885        49       5             Star Wars
4847        4847      888       180       4    Return of the Jedi
4848        4848      553       180       4    Return of the Jedi
4849        4849      799         0       4             Toy Story
4850        4850      576       180       5    Return of the Jedi
4851        4851      793        99       5                 Fargo
4852        4852      733       293       1             Liar Liar
4853        4853      688       257       5               Contact
4854        4854      738        49       4             Star Wars
4855        4855      936       293       1             Liar Liar
4856        4856      873       285       4  English Patient, The
4857        4857      902        49       5             Star Wars
4858        4858      894        99       4                 Fargo
4859        4859      592         0       3             Toy Story
4860        4860      362       180       5    Return of the Jedi
4861        4861      779        49       5             Star Wars
4862        4862      129       120       5      Independence Day

[4863 rows x 5 columns]

In [45]:
# Top 10 movies
movie_reviews_df['movie_title'].unique()

array(['Toy Story', 'Fargo', 'Return of the Jedi', 'Scream', 'Liar Liar',
       'Contact', 'English Patient, The', 'Star Wars', 'Independence Day',
       'Air Force One'], dtype=object)

In [85]:
# Generate the reward column
threshold_val_for_reward = 5
movie_reviews_df['reward'] = movie_reviews_df['rating'].apply(lambda x: 0 if x<threshold_val_for_reward else 1) 

# Generate rewards probabilities for each movie
movie_reviews_output_df = pd.DataFrame(movie_reviews_df.groupby('movie_title').apply(lambda x: sum(x['reward'])/len(x))).reset_index()
movie_reviews_output_df = movie_reviews_output_df.rename({0: 'reward_probabilities'}, axis=1)
movie_reviews_output_df

            movie_title  reward_probabilities
0         Air Force One              0.197216
1               Contact              0.259332
2  English Patient, The              0.272349
3                 Fargo              0.446850
4      Independence Day              0.177156
5             Liar Liar              0.094845
6    Return of the Jedi              0.337278
7                Scream              0.177824
8             Star Wars              0.557461
9             Toy Story              0.263274

In [90]:
# Outputs dataframe to csv
movie_reviews_output_df.to_csv(movie_review_output_path, index=False)